# SPDX-License-Identifier: GPL-3.0-or-later
"""Gemini CLI adapter — custom-theme write + truecolor-stripping wrapper.

Mirrors the claude_code adapter's two-pronged strategy: a JSON setting
swap plus a wrapper that strips COLORTERM behind a sentinel file. The
combination ensures every gemini emission flows through alacritty's
repainted ANSI palette (strict green/amber/red) instead of the raw
truecolor hex that gemini would otherwise emit.

The custom theme mixes two color forms intentionally:

* **ANSI named** ("green", "yellow", "blue", "greenbright" …) for every
  text and status slot. Under the wrapper's COLORTERM strip these emit
  16-color escapes, which alacritty paints to its saab palette exactly.
* **Hex** for the backgrounds. Gemini derives InputBackground /
  MessageBackground / FocusBackground via ``interpolateColor(bg, gray,
  opacity)``; that math wants real numerics on both ends. Passing named
  ANSI colors confuses tinygradient (it reads "blue" as CSS blue rather
  than alacritty's repainted ghost-green), producing a bright-blue
  input box. Hex on both ends keeps the interpolated derivatives near
  the terminal canvas.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Literal

from ..palette import Palette
from .base import Adapter

_LOG = logging.getLogger(__name__)

_SETTINGS = Path.home() / ".gemini" / "settings.json"
_NP_THEME = "nightpanel"  # the customTheme name we write + engage

# Wrapper install paths
_WRAPPER = Path.home() / ".local" / "bin" / "gemini"
_REAL_BIN = Path("/usr/local/bin/gemini")
_NP_ACTIVE = Path.home() / ".config" / "nightpanel" / "nightpanel-active"

_WRAPPER_MARKER = "# nightpanel-gemini-wrapper"

_WRAPPER_SCRIPT = f"""\
#!/usr/bin/env bash
{_WRAPPER_MARKER}
# nightpanel-aware Gemini CLI wrapper.
# When nightpanel is active, strips COLORTERM so any truecolor output
# falls back to 16-color rendering — every escape flows through the
# terminal ANSI palette (which nightpanel paints in strict
# green/amber/red). When nightpanel is off, the wrapper is a transparent
# passthrough. Generated by nightpanel.adapters.gemini_cli — regenerate
# by calling apply().

REAL="{_REAL_BIN}"
if [ ! -x "$REAL" ]; then
    echo "gemini: real binary not found at $REAL" >&2
    exit 127
fi

if [ -e "$HOME/.config/nightpanel/nightpanel-active" ]; then
    exec env -u COLORTERM "$REAL" "$@"
else
    exec "$REAL" "$@"
fi
"""


class GeminiCliAdapter(Adapter):
    name = "gemini_cli"

    def installed(self) -> bool:
        return _REAL_BIN.exists() or _SETTINGS.exists()

    def snapshot(self) -> dict:
        prev = self._read_theme()
        # Don't capture our own applied value as the baseline — revert
        # would then leave the user staring at "nightpanel" after we've
        # torn the custom block down. Fall through to "Default".
        if prev == _NP_THEME:
            prev = None
        return {
            "theme": prev,
            "wrapper_existed": _WRAPPER.exists(),
        }

    def apply(self, palette: Palette) -> None:
        self._write_custom_theme(palette)
        self._write_theme(_NP_THEME)
        self._install_wrapper()

    def revert(self, snapshot: dict) -> None:
        prev = snapshot.get("theme") or "Default"
        self._write_theme(prev)
        # Leave the wrapper in place — it's self-aware via the active-file
        # sentinel and becomes a transparent passthrough when NP is off.

    def verify(self, expected: Literal["on", "off"]) -> bool:
        theme_on = self._read_theme() == _NP_THEME
        wrapper_on = self._wrapper_installed()
        on = theme_on and wrapper_on
        return on if expected == "on" else not on

    # ── helpers ──
    def _read_settings(self) -> dict:
        try:
            return json.loads(_SETTINGS.read_text())
        except (OSError, json.JSONDecodeError):
            return {}

    def _read_theme(self) -> str | None:
        return self._read_settings().get("ui", {}).get("theme")

    def _write_theme(self, value: str) -> None:
        try:
            _SETTINGS.parent.mkdir(parents=True, exist_ok=True)
            data = self._read_settings()
            if "ui" not in data:
                data["ui"] = {}
            data["ui"]["theme"] = value
            _SETTINGS.write_text(json.dumps(data, indent=2) + "\n")
        except OSError as e:
            _LOG.warning("nightpanel: gemini_cli theme write failed: %s", e)

    def _write_custom_theme(self, p: Palette) -> None:
        """Write customThemes.nightpanel with the saab green/amber mapping.

        See module docstring for why text/status use ANSI named colors
        while backgrounds use hex.
        """
        try:
            _SETTINGS.parent.mkdir(parents=True, exist_ok=True)
            data = self._read_settings()
            if "ui" not in data:
                data["ui"] = {}
            if "customThemes" not in data["ui"]:
                data["ui"]["customThemes"] = {}
            data["ui"]["customThemes"][_NP_THEME] = {
                "name": _NP_THEME,
                "type": "custom",
                # All backgrounds clamped to the alacritty canvas. Setting
                # text.secondary as a hex (below) keeps the interpolated
                # InputBackground / MessageBackground / FocusBackground
                # very close to canvas too. The schema is strict —
                # additionalProperties:false on `background`, so only
                # `primary` and `diff` are accepted. Adding `prompt` (which
                # earlier hand-written variants of this theme had) makes
                # gemini reject the entire customTheme and silently fall
                # back to Default — a single shade of green. Don't add it.
                "background": {
                    "primary": p.bg,
                    "diff": {"added": p.bg, "removed": p.bg},
                },
                "text": {
                    # ANSI named — alacritty paints normal.green = p.fg (sage).
                    "primary": "green",
                    # Hex — drives gemini's bg interpolation. fg_mid avoids
                    # landing on any of the alacritty 256-color remap slots
                    # that would render the text as canvas-invisible.
                    "secondary": p.fg_mid,
                    # bright.green = p.fg_bright (live green).
                    "link": "greenbright",
                    # normal.yellow = p.fg_amber (saab needle).
                    "accent": "yellow",
                    "response": "green",
                },
                "status": {
                    "success": "greenbright",
                    "warning": "yellow",
                    "error": "red",
                },
                "ui": {
                    # normal.blue = p.fg_dim (ghost-green) — comments dim.
                    "comment": "blue",
                    # Brackets / separators picked out in amber.
                    "symbol": "yellow",
                    "gradient": ["blue", "green", "greenbright"],
                },
                # Borders come from DarkGray. Setting it explicitly skips
                # gemini's default interpolation (which would yield a faint
                # green tint) and gives a flat subtle grey instead.
                "DarkGray": p.border_d,
            }
            _SETTINGS.write_text(json.dumps(data, indent=2) + "\n")
        except OSError as e:
            _LOG.warning("nightpanel: gemini_cli custom theme write failed: %s", e)

    def _wrapper_installed(self) -> bool:
        """True iff the on-disk wrapper exactly matches _WRAPPER_SCRIPT.

        Marker-only comparison is unsafe: an earlier version of this
        adapter wrote a dumber passthrough script that carried the same
        marker, so a marker check would (and did) leave that stale
        script in place after the COLORTERM-stripping rewrite. Comparing
        full content makes every wrapper change self-healing on the next
        apply().
        """
        if not _WRAPPER.exists() or _WRAPPER.is_symlink():
            return False
        try:
            return _WRAPPER.read_text() == _WRAPPER_SCRIPT
        except OSError:
            return False

    def _install_wrapper(self) -> None:
        if self._wrapper_installed():
            return
        try:
            _WRAPPER.parent.mkdir(parents=True, exist_ok=True)
            if _WRAPPER.is_symlink() or _WRAPPER.exists():
                _WRAPPER.unlink()
            _WRAPPER.write_text(_WRAPPER_SCRIPT)
            _WRAPPER.chmod(0o755)
        except OSError as e:
            _LOG.warning("nightpanel: gemini wrapper install failed: %s", e)
