# SPDX-License-Identifier: GPL-3.0-or-later
"""Render Firefox's userChrome.css from a Palette.

Absorbs the retired `slimfox` project (`~/development/utilities/slimfox`)
plus nightpanel's sharp-corner + thin-border rules. nightpanel is the single
owner of Firefox chrome styling. slimfox was uninstalled from the live profile
on 2026-08-30; only its Tab Session Manager policy scripts survive.

The chrome rules are NOT toggleable per-NP-state — Firefox can't reload
userChrome.css at runtime, only on full restart. The styling is therefore
always-on for the active profile.
"""

from __future__ import annotations

from ..palette import Palette


def render(p: Palette) -> str:
    return f"""\
/* ==========================================================================
   nightpanel — Firefox userChrome
   Canonical source: nightpanel.renderers.firefox_chrome
   Absorbed from:    slimfox/userChrome.css (now retired)

   Two layers stack here:
     A. ULTRA-MINIMAL CHROME (was slimfox): collapse the top toolbox so
        only the page is visible; reveal the URL bar on Ctrl+L (or
        :focused/:open state) and let it retract when focus leaves.
     B. NIGHTPANEL CORNER + BORDER DISCIPLINE: square every chrome
        surface (0px radius), thin {p.border_q} hairline border on
        visible chrome, no Adwaita-style rounding anywhere.

   ESCAPE HATCH: Ctrl+L always summons the URL bar.
   Generated by Python — edit firefox_chrome.py, not this file.
   ========================================================================== */

:root {{
    --slimfox-anim: 0.12s ease;
    /* nightpanel — kill every internal radius knob FF exposes */
    --tab-border-radius: 0 !important;
    --toolbarbutton-border-radius: 0 !important;
    --arrowpanel-border-radius: 0 !important;
    --button-border-radius: 0 !important;
    --urlbar-border-radius: 0 !important;
    --identity-box-border-radius: 0 !important;
}}

/* ── A. MINIMAL CHROME (was slimfox) ─────────────────────────────────────── */

/* 1. Top toolbox = nav/URL bar + bookmarks toolbar + (empty) tab strip.
      Collapse to nothing; reveal on keyboard focus (Ctrl+L). */
#navigator-toolbox {{
    max-height: 0 !important;
    min-height: 0 !important;
    overflow: hidden !important;
    transition: max-height var(--slimfox-anim) !important;
}}

/* Reveal only while Firefox's own urlbar state says it's focused/open.
   The `focused`/`open` attributes are set/cleared by Firefox the instant
   focus leaves the URL bar — retracts reliably, unlike :focus-within in
   XUL chrome which sticks. */
#navigator-toolbox:has(#urlbar[focused]),
#navigator-toolbox:has(#urlbar[open]) {{
    max-height: 120px !important;
}}

/* The URL bar's "breakout" pill is hidden when not in use. opacity (not
   visibility/display) keeps it focusable, so Ctrl+L still summons it. */
#urlbar:not([focused]):not([open]) {{
    opacity: 0 !important;
    pointer-events: none !important;
}}

/* 2. Vertical-tabs sidebar = the tab list. NOT hidden by CSS, on purpose.
      Visibility is Firefox's job here, driven by sidebar.visibility=
      hide-sidebar: the launcher starts hidden every session and Ctrl+Alt+Z
      summons it. A `display:none` rule here would defeat that key, since
      CSS cannot respond to a keypress — that was the pre-0.2.8 bug, where
      the sidebar read as permanently disabled.

      Do NOT pin a min-width on #sidebar-main either. That forces the rail
      back on screen and re-breaks hide-sidebar.

      Only the non-tab sidebar tool buttons (history/synced/bookmarks panel
      icons) are hidden, for a leaner rail once summoned. We deliberately do
      NOT hide #sidebar-box: in the ESR 140 revamp layout it contains the
      vertical-tabs launcher, so hiding it takes the tab rail with it.
      Selectors are best-effort across versions; harmless if they miss.
      Requires sidebar.revamp + sidebar.verticalTabs + sidebar.expandOnHover
      =false (expandOnHover is mutually exclusive with the manual toggle —
      leaving it on no-ops Ctrl+Alt+Z). */
#sidebar-main toolbarbutton[data-l10n-id="sidebar-menu-history-label"],
#sidebar-main toolbarbutton[data-l10n-id="sidebar-menu-synced-tabs-label"],
#sidebar-main toolbarbutton[data-l10n-id="sidebar-menu-bookmarks-label"] {{
    display: none !important;
}}

/* 3. Bookmarks toolbar, regardless of its show/hide state. */
#PersonalToolbar {{
    visibility: collapse !important;
}}

/* 4. Belt-and-suspenders for the classic horizontal tab strip
      (harmless when vertical tabs are active). */
#TabsToolbar {{
    visibility: collapse !important;
}}

/* 5. Reclaim every pixel the chrome used to occupy. */
#browser,
#appcontent,
#tabbrowser-tabbox {{
    margin: 0 !important;
}}

/* ── B. NIGHTPANEL CORNER + BORDER DISCIPLINE ────────────────────────────── */

/* Top-level window + chrome containers */
#main-window,
#navigator-toolbox,
#tabbrowser-tabs,
.tabbrowser-tab,
.tab-content,
.tab-background,
#nav-bar,
#urlbar,
#urlbar-input-container,
#urlbar-background,
#searchbar,
.searchbar-textbox,
.toolbarbutton-1,
.toolbarbutton-icon,
#identity-box,
.identity-box-button {{
    border-radius: 0 !important;
}}

/* Popups, menus, autocomplete */
menupopup,
panel,
.panel-arrowcontent,
.subviewbutton,
.menu-iconic,
#PopupAutoComplete,
#urlbar-results,
.urlbarView-row,
.autocomplete-richlistbox,
notification-message,
.popup-notification {{
    border-radius: 0 !important;
}}

/* Thin NP border on the briefly-revealed URL bar (the one chrome element
   visible during normal use). The hairline grey keeps it readable against
   the page-content canvas without competing with text. */
#navigator-toolbox:has(#urlbar[focused]),
#navigator-toolbox:has(#urlbar[open]) {{
    border-bottom: 1px solid {p.border_q};
}}
"""
